[build-system]
requires = ["setuptools", "wheel", "scikit-build", "cmake", "pybind11", "ninja"]
build-backend = "setuptools.build_meta"

[pytest]
testpaths = "test/python"
norecursedirs = "extern/*"

[tool.flake8]
max-line-length=100

[tool.black]
line-length=100