[build-system]
requires = ["setuptools", "wheel", "scikit-build", "cmake", "pybind11", "ninja"]
build-backend = "setuptools.build_meta"

[pytest]
testpaths = "test/python"
norecursedirs = "extern/*"

[flake8]
max-line-length=100