---
title: "Ball-by-ball EDA"
output:
  html_document:
    theme: spacelab
    number_sections: yes
    df_print: paged
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

pacman::p_load(tidyverse, corrplot)

# Load
bbb <- readRDS("bbb_cleaned.rds")


bbb <- bbb %>% add_column(runs_int = as.numeric(levels(bbb$runs))[bbb$runs])

rescale01 <- function(x) {
  rng <- range(x, na.rm = TRUE)
  (x - rng[1]) / (rng[2] - rng[1])
}

# Normalise pitch factors
bbb <- bbb %>% mutate_at(c("seam_factor", "spin_factor"), rescale01) %>%
  mutate(n_seam_factor = seam_factor/(seam_factor + spin_factor), n_spin_factor = spin_factor/(seam_factor + spin_factor)) %>% 
  select(-c(seam_factor, spin_factor)) %>%
  rename(seam_factor = n_seam_factor, spin_factor = n_spin_factor)


# For calculating mode
Mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

```


# Summary
```{r}
skimr::skim(bbb)
```

# Univariate Relationships

## Histograms
```{r}
bbb %>% ggplot(aes(match_balls)) + geom_histogram(bins = 50, fill = "maroon", colour = "black")
```

```{r}
bbb %>% ggplot(aes(inn_balls)) + geom_histogram(bins = 50, fill = "maroon", colour = "black")
```


```{r}
bbb %>% ggplot(aes(team_score)) + geom_histogram(bins = 50, fill = "maroon", colour = "black")
```

```{r}
bbb %>% ggplot(aes(team_lead)) + geom_histogram(bins = 50, fill = "maroon", colour = "black")
```
```{r}
bbb %>% ggplot(aes(sample = team_lead)) +
    stat_qq() +
    stat_qq_line()

```



```{r}
bbb %>% ggplot(aes(bat_score)) + geom_histogram(bins = 50, fill = "maroon", colour = "black")
```


```{r}
bbb %>% ggplot(aes(bat_balls)) + geom_histogram(bins = 50, fill = "maroon", colour = "black")
```


```{r}
bbb %>% ggplot(aes(bat_avg)) + geom_histogram(bins = 50, fill = "maroon", colour = "black")
```

```{r}
bbb %>% ggplot(aes(career_bat_balls)) + geom_histogram(bins = 50, fill = "maroon", colour = "black")
```


```{r}
bbb %>% ggplot(aes(bat_sr)) + geom_histogram(bins = 50, fill = "maroon", colour = "black")
```

```{r}
bbb %>% ggplot(aes(bowl_balls)) + geom_histogram(bins = 50, fill = "maroon", colour = "black")
```


```{r}
bbb %>% ggplot(aes(bowl_runs)) + geom_histogram(bins = 50, fill = "maroon", colour = "black")
```

```{r}
bbb %>% ggplot(aes(career_bowl_balls)) + geom_histogram(bins = 50, fill = "maroon", colour = "black")
```

```{r}
bbb %>% filter(career_bowl_balls > 3000) %>% ggplot(aes(bowl_avg)) + geom_histogram(bins = 50, fill = "maroon", colour = "black")
```

```{r}
bbb %>% ggplot(aes(seam_factor)) + geom_histogram(bins = 50, fill = "maroon", colour = "black")
```

```{r}
bbb %>% group_by(game_id) %>% summarise(x = mean(seam_factor)) %>% ggplot(aes(sample = x)) +
    stat_qq() +
    stat_qq_line()

```




```{r}
bbb %>% ggplot(aes(spin_factor)) + geom_histogram(bins = 50, fill = "maroon", colour = "black")
```

```{r}
bbb %>% group_by(game_id) %>% summarise(x = mean(spin_factor)) %>% ggplot(aes(sample = x)) +
    stat_qq() +
    stat_qq_line()

```



## Predictors
```{r}
bbb %>% ggplot(aes(x = runs)) + geom_bar()
```




# Bivariate Relationships
```{r}
bbb %>% select_if(is.numeric) %>% na.omit() %>% cor() %>% corrplot()
```


## Wickets
```{r}
bbb %>% filter(inn_balls < 1000) %>% group_by(inn_balls) %>% summarise(wp = length(is_wkt[is_wkt == "W"])/n()) %>% ggplot(aes(x = inn_balls, y = wp)) + geom_point()

```



```{r}
bt_ba_sum <- bbb %>% na.omit() %>% filter(bowl_type %in% c("lfm", "lf", "lo", "rfm", "rf", "rls", "rob")) %>% group_by(bowl_type, bat_arm) %>% summarise(wp = mean(as.integer(is_wkt))/n())

ggplot(aes(x = bowl_type, y = wp, color = "Right"), data = bt_ba_sum %>% filter(bat_arm == "Right-hand bat")) + geom_point() +
  geom_point(aes(x = bowl_type, y = wp, color = "Left"), data = bt_ba_sum %>% filter(bat_arm == "Left-hand bat"))

```

```{r}
hc_bc_sum <- bbb %>% na.omit() %>% group_by(host_country, bowl_class) %>% summarise(wc = sum(as.integer(is_wkt[is_wkt == "W"]) - 1), n = n()) %>% mutate(wp = wc/n)

ggplot(aes(x = host_country, y = wp, color = "Seam"), data = hc_bc_sum %>% filter(bowl_class == "seam")) + geom_point() +
  geom_point(aes(x = host_country, y = wp, color = "Spin"), data = hc_bc_sum %>% filter(bowl_class == "spin"))

```


## Runs
```{r}
bbb %>% filter(bat_sr < 100) %>% group_by(bat_sr) %>% summarise(sr = 100*sum(runs_int)/n()) %>% ggplot(aes(x = bat_sr, y = sr)) + geom_point() +
  xlab("Career Strike Rate") +
  ylab("Observed Strike Rate")

```


```{r}
bbb %>% group_by(team_wkts) %>% summarise(sr = 100*sum(runs_int)/n()) %>% ggplot(aes(x = team_wkts, y = sr)) + geom_point() +
  xlab("Wickets Fallen") +
  ylab("Observed Strike Rate")

```

```{r}
bbb %>% group_by(bat_position) %>% summarise(sr = 100*sum(runs_int)/n()) %>% ggplot(aes(x = bat_position, y = sr)) + geom_point() +
  xlab("Batting Position") +
  ylab("Observed Strike Rate")

```



```{r}
bbb %>% group_by(team_wkts, bat_position) %>% summarise(sr = 100*sum(runs_int)/n()) %>% ggplot(aes(x = team_wkts, y = bat_position, color = sr, size = sr)) + geom_point() +
  xlab("Wickets Fallen") +
  ylab("Batting Position")

```



```{r}
bbb %>% filter(abs(team_lead) < 450) %>% group_by(team_lead) %>% summarise(sr = 100*sum(runs_int)/n()) %>% ggplot(aes(x = team_lead, y = sr)) + geom_point() +
  xlab("Team Lead") +
  ylab("Observed Strike Rate")

```


```{r}
bbb %>% filter(bowl_balls < 375) %>% group_by(bowl_balls) %>% summarise(sr = 100*sum(runs_int)/n()) %>% ggplot(aes(x = bowl_balls, y = sr)) + geom_point() +
  xlab("Balls Bowled by Bowler") +
  ylab("Observed Strike Rate")

```



```{r}
bbb %>% filter(bat_balls < 450) %>% group_by(bat_balls) %>% summarise(sr = 100*sum(runs_int)/n()) %>% ggplot(aes(x = bat_balls, y = sr)) + geom_point() +
  xlab("Balls Faced by Batter") +
  ylab("Observed Strike Rate")

```

```{r}
bbb %>% filter(inn_balls < 1000) %>% group_by(inn_balls) %>% summarise(sr = 100*sum(runs_int)/n()) %>% ggplot(aes(x = inn_balls, y = sr)) + geom_point() +
  xlab("Balls in Innings") +
  ylab("Observed Strike Rate")

```




# Pitch Factors - by Venue
```{r}
bbb %>% na.omit() %>% group_by(host_country) %>% summarise(seam = mean(seam_factor), spin = mean(spin_factor)) %>% ggplot(aes(host_country, seam, color = 'Seam Factor')) + geom_point(color = 'red') + geom_point(aes(y = spin), color = 'blue')

```

## Most Played Venues
```{r}
bbb %>% na.omit() %>% group_by(venue) %>% summarise(n = n(), country = Mode(host_country), seam = mean(seam_factor), spin = mean(spin_factor))
```




# Coin Toss Analysis
Investigating relationship between decision at the toss and the pitch factors, to determine an appropriate model.
```{r}
tmp <- bbb %>% na.omit() %>% group_by(game_id) %>% summarize(toss_elect = first(toss_elect), seam_factor = mean(seam_factor), spin_factor = mean(spin_factor)) %>% mutate(bin = cut(seam_factor, breaks = seq(from = 0, to = 1, by = 0.05))) %>% group_by(bin,toss_elect, .drop = FALSE) %>% summarise(n = n())

toss_df <- tibble(bin = unique(tmp$bin), n_field = (tmp %>% filter(toss_elect == "field"))$n, n_bat = (tmp %>% filter(toss_elect == "bat"))$n) %>%
  mutate(n = n_field + n_bat) %>% 
  mutate(field_prob = n_field/n)

a <- 0.1
b <- log(0.8/a)
toss_model <- data.frame(x = 1:21) %>% mutate(y = a*exp(b*seq(from = 0, to = 1, by = 0.05)))
toss_df %>% ggplot(aes(bin,field_prob)) + geom_col() + geom_line(aes(x,y), data = toss_model)

```







