---
title: "Ball-By-Ball Data Visualisation"
author: "L.Blake"
date: "13/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, ggfortify, corrplot)

bbb <- readRDS('bbb_wkt.RDS')
```



```{r}

bbb %>% 
  group_by(bowl_type) %>%
  summarise(no_wkts = sum(is_wkt == "W"))

```


# Scatterplots
```{r}

bbb %>% ggplot(aes(bowl_avg, bat_avg, color = is_wkt)) + geom_point(alpha = 0.5)


```



```{r}
num_dat <-bbb %>% select(-where(is.factor), is_wkt) %>% na.omit(where(is.numeric))
pca <- prcomp(num_dat %>% select(-is_wkt))
autoplot(pca, data = num_dat, colour = "wicket")

```





```{r}
c_all <- bbb %>% group_by(host_country) %>% tally()
c_seam <- bbb %>% filter(bowl_class == "seam" & is_wkt == "W") %>% group_by(host_country) %>% tally()
c_spin <- bbb %>% filter(bowl_class == "spin" & is_wkt == "W") %>% group_by(host_country) %>% tally()
c_seam[,2] <- c_seam[,2]/c_all[,2]
c_seam %>% mutate(spin = c_spin[,2]/c_all[,2]) %>% mutate(diff = abs(n - spin)) %>% ggplot(aes(x = fct_reorder(host_country, diff$n))) + geom_point(aes(y = n, color = "Seam")) + geom_point(aes(y =  spin$n, color = "Spin")) + labs(x = "Host Country", y = "Wicket Proportion", color = "Bowl Type") + scale_color_manual(values = c("Spin" = "red", "Seam" = "blue"))


```



```{r}
all_bp <- bbb %>% group_by(bat_position) %>% tally()
wk_bp <- bbb %>% filter(is_wkt == "W") %>% group_by(bat_position) %>% tally()

wk_bp[,2] <- wk_bp[,2]/all_bp[,2]
wk_bp %>% ggplot(aes(bat_position, n)) + geom_point()
```

```{r}
all_bf <- bbb %>% group_by(bat_balls) %>% tally()
wk_bf <- bbb %>% filter(is_wkt == "W") %>% group_by(bat_balls) %>% tally()

wk_bf[,2] <- wk_bf[,2]/all_bf[,2]
wk_bf %>% ggplot(aes(bat_balls, n)) + geom_point()
```



```{r}
bbb %>% select_if(is.numeric) %>% 
  na.omit() %>%
  cor() %>% 
  corrplot()

```