name: Build and Test (Ubuntu)

on:
  pull_request: 
    branches: [master]
  push: 
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # install Boost libraries
    - name: Install Boost
      run: sudo apt-get update && sudo apt-get install -yq libboost-all-dev

    # build project
    - name: Create build environment
      run: mkdir build

    - name: Build
      run: cmake -Bbuild -H.

    - name: Make
      run: cmake --build build/ --target all

    - name: List
      run: ls
      
    # run tests
    - name: Run unit tests
      run: ctest