# Runs all required checks of any code being committed to the main branch 
name: code checks

on:
  pull_request: 
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Boost
      run: sudo apt-get update && sudo apt-get install -yq libboost-all-dev

    - name: Create build environment
      run: mkdir build

    - name: Build
      run: cmake -Bbuild -H.

    - name: Make
      run: cmake --build build/ --target all

    - name: Archive built files
      uses: actions/upload-artifact@v2
      with:
        name: build
        #TODO: Optimise this to ignore unnessecary files
        path: |
          build

  tests:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download built files
      uses: actions/download-artifact@v2
      with:
        name: build

    - name: ls
      run: ls

    - name: Run unit tests
      run: cd build && ctest --verbose

    - name: Run simulation demo
      run: cd build/test && ./demo_test

  linter:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: '.'
        extensions: 'h,cpp'
        clangFormatVersion: 11
        exclude: test/*
