# Runs all required checks of any code being committed to the main branch 
name: code checks

on:
  pull_request: 
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:


jobs:

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      faile-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Boost
      run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update && sudo apt-get install -yq libboost-all-dev
          elif ["$RUNNER_OS" == "Mac"]; then
            brew install boost
          fi

    - name: ls
      run: ls

    - name: Create build environment
      run: mkdir build

    - name: Build
      run: cmake -Bbuild -H.

    - name: Make
      run: cmake --build build/ --target all

    - name: Run unit tests
      run: cd build && ctest --verbose

    - name: Run simulation demo
      run: cd build/test && ./demo_test

  linter:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: 'src include'
        extensions: 'h,cpp'
        clangFormatVersion: 11
        exclude: test/*
