name: Generate Doxygen Documentation

on:
  pull_request:
    branches: [master]
  push: 
    branches:
      - master 
      - develop-doxygen

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: mattnotmitt/doxygen-action@v1
      with:
        working-directory: 'submodule/'
        doxyfile-path: './doc/Doxyfile'
        enable-latex: false