name: Code style

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.12
        with:
          source: "src include"
          extensions: "h,cpp"
          clangFormatVersion: 11
          exclude: test/* extern/*

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install package and dependencies
        run: python -m pip install -e .[dev]

      - name: Lint with flake8
        run: flake8 src/testmatch

      - name: Lint with black
        run: black --check src/testmatch

      - name: Type checking with mypy
        run: mypy src/testmatch